In [1]:
using Tensors

# 2階のテンソルを作成
T = Tensor{2, 3, Float64}([1 2 3; 4 5 6; 7 8 9])
println(T)

# 行列演算
println(T + T)       # 加算
println(det(T))      # 行列式

[1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]
[2.0 4.0 6.0; 8.0 10.0 12.0; 14.0 16.0 18.0]
0.0


In [2]:
T


3×3 Tensor{2, 3, Float64, 9}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [3]:
T = Tensor{3, 3, Float64}([
    1,  2,  3,  4,  5,  6,  7,  8,  9,
    10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25, 26, 27
])

3×3×3 Tensor{3, 3, Float64, 27}:
[:, :, 1] =
 1.0  4.0  7.0
 2.0  5.0  8.0
 3.0  6.0  9.0

[:, :, 2] =
 10.0  13.0  16.0
 11.0  14.0  17.0
 12.0  15.0  18.0

[:, :, 3] =
 19.0  22.0  25.0
 20.0  23.0  26.0
 21.0  24.0  27.0

In [4]:
using TensorOperations
α = randn()
A = randn(5, 5, 5, 5, 5, 5)
B = randn(5, 5, 5)
C = randn(5, 5, 5)
D = zeros(5, 5, 5)
@tensor begin
    D[a, b, c] = A[a, e, f, c, f, g] * B[g, b, e] + α * C[c, a, b]
    E[a, b, c] := A[a, e, f, c, f, g] * B[g, b, e] + α * C[c, a, b]
end

5×5×5 Array{Float64, 3}:
[:, :, 1] =
  15.6108    -21.1103      7.54189  -13.7271     7.36737
  -0.366541    0.752057   -6.73885   -8.90531  -11.2684
 -11.7615      1.50415     2.31277   -1.03196  -17.2714
  24.2475     -0.656294   -7.60265  -14.8187    -0.0428629
  10.4023     18.7409    -20.8992    18.9238     6.5271

[:, :, 2] =
  7.90661     -9.8769    -13.9871   -0.216374   13.4649
  9.6574     -10.3695      7.46386  14.5923      8.16537
  3.10036      6.72476   -11.6751    1.43803     3.8055
 -6.96421     -0.384532   24.4491   -6.4838    -29.8184
 -0.0995512  -10.8024     12.4477   -1.09157     2.57292

[:, :, 3] =
 -11.5698   -7.88991   18.4788    4.34777   -5.78236
   9.29695  -6.49627   21.2844   -8.08845   11.6318
   8.0214    3.80913    7.60189  20.3224     6.16843
  -1.85518   0.156828  -2.92694  12.1262   -22.0724
  -6.51435  16.1203    -3.86535  -7.21054   -4.61012

[:, :, 4] =
   3.06274  -6.8444     6.57042    5.80456  22.832
 -16.083     0.601768  -2.32347  -17.1185   

In [5]:
B

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -0.511334   0.635734  -1.697       0.1496    -2.40672
 -0.103569  -0.646138   0.0300294  -2.13626    0.884548
  0.746606   0.238182   1.3417     -0.317195   0.327054
 -1.95882   -1.56979   -0.216693   -1.15729    0.545007
  0.153176   0.035695  -0.534832    0.392199   0.661379

[:, :, 2] =
 -0.599377   -0.892937  -1.71741   -0.558804  -0.867564
  0.0423005  -0.892233   0.920248   1.13301    2.19458
  0.496315    0.571815  -1.65839   -1.17113   -1.26835
 -0.795014    0.391549   0.447971  -3.55826   -0.0103868
  0.70684    -1.58528    0.347056   3.17499    1.40607

[:, :, 3] =
 -0.0343819  -0.541987   1.1377     -0.0663477  -0.754356
 -1.43918    -1.53766   -0.0859285  -0.229342   -1.59855
  0.344656   -0.565912   0.18286    -1.03437    -0.212527
  0.762481    0.792672  -0.760441   -0.893456    3.35617
 -1.45608    -0.945236  -0.230508   -0.254386   -0.283505

[:, :, 4] =
  1.36767   -0.31642    0.280853   0.837234   -1.52239
 -0.624512   0.172412   

In [15]:

@variables a b c
x_functional = [a * i + b * j for i in 1:3, j in 1:3]
y_functional = [b * i - c * j for i in 1:3, j in 1:3]

# 縮約計算を明示
z = [expand(x_functional[i, j] * y_functional[j, k]) for i in 1:3, j in 1:3, k in 1:3]
println("z[i, k] = $z")



z[i, k] = [a*b - a*c + b^2 - b*c 2a*b - a*c + 4(b^2) - 2b*c 3a*b - a*c + 9(b^2) - 3b*c; 2a*b - 2a*c + b^2 - b*c 4a*b - 2a*c + 4(b^2) - 2b*c 6a*b - 2a*c + 9(b^2) - 3b*c; 3a*b - 3a*c + b^2 - b*c 6a*b - 3a*c + 4(b^2) - 2b*c 9a*b - 3a*c + 9(b^2) - 3b*c;;; a*b - 2a*c + b^2 - 2b*c 2a*b - 2a*c + 4(b^2) - 4b*c 3a*b - 2a*c + 9(b^2) - 6b*c; 2a*b - 4a*c + b^2 - 2b*c 4a*b - 4a*c + 4(b^2) - 4b*c 6a*b - 4a*c + 9(b^2) - 6b*c; 3a*b - 6a*c + b^2 - 2b*c 6a*b - 6a*c + 4(b^2) - 4b*c 9a*b - 6a*c + 9(b^2) - 6b*c;;; a*b - 3a*c + b^2 - 3b*c 2a*b - 3a*c + 4(b^2) - 6b*c 3a*b - 3a*c + 9(b^2) - 9b*c; 2a*b - 6a*c + b^2 - 3b*c 4a*b - 6a*c + 4(b^2) - 6b*c 6a*b - 6a*c + 9(b^2) - 9b*c; 3a*b - 9a*c + b^2 - 3b*c 6a*b - 9a*c + 4(b^2) - 6b*c 9a*b - 9a*c + 9(b^2) - 9b*c]


In [16]:
using Symbolics
@variables x
quintic = x^5 + x ~ 1

x + x^5 ~ 1

In [17]:
function solve_newton(eq, x, x₀; abstol=1e-8, maxiters=50)
    # symbolic expressions for f(x) and f′(x)
    f = eq.lhs - eq.rhs # want to find root of f(x)
    f′ = Symbolics.derivative(f, x)

    xₙ = x₀ # numerical value of the initial guess
    for i = 1:maxiters
        # calculate new guess by numerically evaluating symbolic expression at previous guess
        xₙ₊₁ = substitute(x - f / f′, x => xₙ)
        if abs(xₙ₊₁ - xₙ) < abstol
            return xₙ₊₁ # converged
        else
            xₙ = xₙ₊₁
        end
    end
    error("Newton's method failed to converge")
end

x_newton = solve_newton(quintic, x, 1.0)
println("Newton's method solution: x = ", x_newton)

Newton's method solution: x = 0.7548776662466927


In [18]:
using Symbolics

# シンボリック変数の定義
@variables x[1:3, 1:3] y[1:3, 1:3] z[1:3, 1:3]
@variables a b c

# テンソルの要素をシンボリック式で割り当て
x = [a * i + b * j for i in 1:3, j in 1:3]
y = [b * i - c * j for i in 1:3, j in 1:3]

# 内積計算
z = zeros(Symbolics.Num, 3, 3)  # 結果テンソルの初期化
for i in 1:3, j in 1:3
    z[i, j] = sum(x[i, k] * y[k, j] for k in 1:3)  # 縮約計算
end

println("z = $z")


z = Num[(a + 3b)*(3b - c) + (a + b)*(b - c) + (a + 2b)*(2b - c) (a + 2b)*(2b - 2c) + (a + 3b)*(3b - 2c) + (a + b)*(b - 2c) (a + b)*(b - 3c) + (a + 3b)*(3b - 3c) + (a + 2b)*(2b - 3c); (2a + 2b)*(2b - c) + (2a + b)*(b - c) + (2a + 3b)*(3b - c) (2a + 2b)*(2b - 2c) + (2a + 3b)*(3b - 2c) + (2a + b)*(b - 2c) (2a + b)*(b - 3c) + (2a + 3b)*(3b - 3c) + (2a + 2b)*(2b - 3c); (3a + 3b)*(3b - c) + (3a + b)*(b - c) + (3a + 2b)*(2b - c) (3a + b)*(b - 2c) + (3a + 3b)*(3b - 2c) + (3a + 2b)*(2b - 2c) (3a + 2b)*(2b - 3c) + (3a + 3b)*(3b - 3c) + (3a + b)*(b - 3c)]


In [19]:
# シンボリック変数の定義
@variables x y z

# スカラー関数の定義
f = x^2 + y^2 + z^2

# f の勾配を計算
grad_f = [Differential(x)(f), Differential(y)(f), Differential(z)(f)]
println("Gradient of f: $grad_f")


Gradient of f: Num[Differential(x)(x^2 + y^2 + z^2), Differential(y)(x^2 + y^2 + z^2), Differential(z)(x^2 + y^2 + z^2)]


In [21]:
# ベクトル場の定義
F = [x^2, y^2, z^2]

# 発散を計算
div_F = Differential(x)(F[1]) + Differential(y)(F[2]) + Differential(z)(F[3])
println("Divergence of F: $div_F")


Divergence of F: Differential(x)(x^2) + Differential(y)(y^2) + Differential(z)(z^2)


In [22]:
# ベクトル場の定義
F = [x^2, y^2, z^2]

# 回転（カール）を計算
curl_F = [
    Differential(y)(F[3]) - Differential(z)(F[2]),
    Differential(z)(F[1]) - Differential(x)(F[3]),
    Differential(x)(F[2]) - Differential(y)(F[1])
]
println("Curl of F: $curl_F")

Curl of F: Num[-Differential(z)(y^2) + Differential(y)(z^2), Differential(z)(x^2) - Differential(x)(z^2), -Differential(y)(x^2) + Differential(x)(y^2)]


In [24]:
import Pkg; Pkg.add("DifferentialForms")

   Resolving package versions...
   Installed ComputedFieldTypes ─ v1.0.2
   Installed DifferentialForms ── v3.2.1
    Updating `/opt/julia/environments/v1.9/Project.toml`
  [9e54b8bf] + DifferentialForms v3.2.1
    Updating `/opt/julia/environments/v1.9/Manifest.toml`
  [459fdd68] + ComputedFieldTypes v1.0.2
  [9e54b8bf] + DifferentialForms v3.2.1
Precompiling project...
  ✓ ComputedFieldTypes
  ✓ DifferentialForms
  2 dependencies successfully precompiled in 62 seconds. 401 already precompiled.


In [43]:
using DifferentialForms
using Symbolics


In [40]:
v = Form{3,1}((1, 2, 3))

Int64{3,1}⟦[1]:1, [2]:2, [3]:3⟧

In [41]:
 a = Form{3,2}((1, 2, 3))

Int64{3,2}⟦[12]:1, [13]:2, [23]:3⟧

In [42]:
q = v ∧ a

Int64{3,3}⟦[123]:2⟧

In [44]:
Pkg.add("Grassmann")

   Resolving package versions...
   Installed AbstractTensors ── v0.8.8
   Installed StaticVectors ──── v1.0.7
   Installed Leibniz ────────── v0.2.9
   Installed DirectSum ──────── v0.8.17
   Installed Grassmann ──────── v0.8.27
   Installed AbstractLattices ─ v0.3.1
    Updating `/opt/julia/environments/v1.9/Project.toml`
  [4df31cd9] + Grassmann v0.8.27
    Updating `/opt/julia/environments/v1.9/Manifest.toml`
  [398f06c4] + AbstractLattices v0.3.1
  [a8e43f4a] + AbstractTensors v0.8.8
  [22fd7b30] + DirectSum v0.8.17
  [4df31cd9] + Grassmann v0.8.27
  [edad4870] + Leibniz v0.2.9
  [20fadf95] + StaticVectors v1.0.7
Precompiling project...
  ✓ StaticVectors
  ✓ AbstractLattices
  ✓ AbstractTensors
  ✓ Leibniz
  ✓ DirectSum
  ✓ Grassmann
  6 dependencies successfully precompiled in 158 seconds. 403 already precompiled.


In [45]:
using Grassmann


In [46]:
G2=Λ(2)

DirectSum.Basis{⟨11⟩,4}(v, v₁, v₂, v₁₂)

In [47]:
u2=[2,1]

2-element Vector{Int64}:
 2
 1

In [48]:
w2=[1
       -2]


2-element Vector{Int64}:
  1
 -2